# Config file for automatic testing at travis-ci.org
sudo: false

notifications:
  email: false

language: python
python: 3.5
addons:
    mariadb: 10.0

install:
  - pip install tox

script: HYPOTHESIS_MAX_EXAMPLES=1000 tox
