dist: xenial
sudo: required

notifications:
  email: false

language: python
cache: pip

services:
- docker

matrix:
  include:
  - python: 3.5
  - python: 3.6
  - python: 3.7
  - python: 3.8
  - python: 3.9-dev

before_script: .travis/before_script.sh

install: pip install tox-travis

script: HYPOTHESIS_MAX_EXAMPLES=1000 tox
