# Config file for automatic testing at travis-ci.org
sudo: required

notifications:
  email: false

language: python

before_script: .travis/before_script.sh

install:
  - pip install tox

script: HYPOTHESIS_MAX_EXAMPLES=1000 tox
