sudo: false
dist: xenial

notifications:
  email: false

language: python
cache: pip
addons:
  mariadb: 10.4

matrix:
  include:
  - python: 3.5
  - python: 3.6
  - python: 3.7
  - python: 3.8

install:
- mysql -u root -e 'SET GLOBAL max_allowed_packet = 1048576000'
# To fix this issue: https://travis-ci.community/t/mariadb-10-1-fails-to-install-on-xenial/3151/3
- mysql -u root -e 'CREATE USER IF NOT EXISTS travis@localhost; GRANT ALL ON *.* TO travis@localhost;'
- pip install tox-travis

script: HYPOTHESIS_MAX_EXAMPLES=1000 tox
